python3-stylecheck:
  image: python:3.6.9
  stage: test
  script:
    - pip install flake8
    - flake8
  tags:
    - docker

python3-tests:
  image: python:3.6.9
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test
  tags:
    - docker

docker-build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t newsfeed .
  tags:
    - docker

docs:
  image: python:3.6.9
  stage: test
  script:
  tags:
    - docker
