# Generated by Django 3.1.7 on 2021-04-03 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('source_country', models.CharField(blank=True, max_length=100, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_link', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
