# Generated by Django 3.1.7 on 2021-04-15 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadListNewsBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.URLField()),
                ('source_of_news', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_news', models.CharField(blank=True, max_length=100, null=True)),
                ('original_news_source_link', models.URLField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('readlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.readlist')),
            ],
            options={
                'verbose_name': 'ReadListNewsBody',
                'verbose_name_plural': 'ReadListNewsBodies',
            },
        ),
        migrations.RemoveField(
            model_name='newsreader',
            name='reader',
        ),
        migrations.DeleteModel(
            name='NewsBody',
        ),
        migrations.DeleteModel(
            name='NewsReader',
        ),
    ]
