# Generated by Django 3.1.7 on 2021-04-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
