# Generated by Django 3.1.7 on 2021-04-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='keywords_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='news_source_tags',
        ),
        migrations.CreateModel(
            name='RecommendTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_tags', jsonfield.fields.JSONField(max_length=1000)),
                ('news_source_tags', jsonfield.fields.JSONField(max_length=1000)),
                ('keywords_tags', jsonfield.fields.JSONField(max_length=1000)),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
