# Generated by Django 3.1.7 on 2021-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210410_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Checking this box will send you newsletters to your email id about the latest news updates(within every 15 minutes) based on this readlist. To stop getting news please set this field unchecked'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False, help_text='This will enlist you to newsletter feature. You will get newsletter emails on latest news updates(within every 15 minutes). To stop getting news please set this field unchecked'),
        ),
    ]
