# Generated by Django 3.1.7 on 2021-04-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210407_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscard',
            old_name='source_country',
            new_name='country_of_news',
        ),
        migrations.RenameField(
            model_name='newscard',
            old_name='source_link',
            new_name='original_news_source_link',
        ),
        migrations.RenameField(
            model_name='newscard',
            old_name='source_name',
            new_name='source_of_news',
        ),
        migrations.RenameField(
            model_name='newscard',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='newscard',
            name='published_at',
        ),
    ]
