# Generated by Django 3.1.7 on 2021-04-07 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210407_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscard',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
